### ISSUE TITLE
Add detection against use of third party macro programs

### ISSUE THREAD

**Issue by Smittytron** [OpenRA/OpenRA#14999]
An unfortunate development in the competitive scene has been the proliferation of third party macro programs. These programs allow one button press to act as several. In the case of a single queue production system like RA, this effectively allows automated production. What once took a heckuva lot of practice to learn can now be done in a single key press.

Blizzard bans the use of these programs; for good reason. I assume they do it by detecting an inhuman amount of simultaneous commands. I’ve seen the APM (according to how OpenRA records APM) of players shoot up from the 40s to the 80s-90s range.

**Comment by Stx3000** [comment]
I see [here](https://en.wikipedia.org/wiki/Actions_per_minute) "Beginners often have low APM counts, typically below 50."
So going from 40 to 80 could be "oh I have something to do now".

**Comment by HappyORA** [comment]
@ghost
average player apm in the competitive scene is 30. Mine is usually 40-50 and can shoot to 70 when intensely using air units.

I don't think there will be a way of detecting it be made possible. The fortunate development is anyone can use a macro problem.

**Comment by MunWolf** [comment]
Usually these programs detect spikes in eAPM instead of APM as that is far harder then getting your apm up, for example clicking 40 times in a single spot to micro air units is going to shoot your apm up while your effective APM stays very low.
This of course can become a false positive as well though it is much harder.

However I don't see any of the current developers having the time/energy/interest to work on this.

If you feel strongly about it you can always try implementing it yourself and submitting a pull request.

Development is hard enough and forcing yourself to develop something that you have no interest and gives you no monetary value is even worse.

**Comment by anjew175** [comment]
I see this being worth too much effort for what is virtually a non-problem. Let alone the possibility of false positives (lag spikes sending all orders or just straight up actually being fast). The benefits from using a macro are slight, if not, none existent against a competent player of equal skill. 

The million dollar question though is, what would you do when you detect it?
Would you have players banned from OpenRA? Kicked from the game? Blacklisted from servers?

It's one thing to detect but if you want to enforce a punishment then the punishment far outweighs the crime.

Worth noting that macros can be made to add delays between key presses, effectively circumventing detection via APM

**Comment by CatGirls420-NerevarII** [comment]
Macros give an unfair advantage and save a lot of time, especially over the course of a match. NOT preventing would be a bad thing, unless everyone starts using macros. I know several "top players" who use macros, and makes me wonder how well they would play without it.
If there's competitive play, especially in something like RAGL, macros are borderline cheating, if not cheating.

Like smitty said, blizzard implements anti-macro, and for many, very good, reasons.

**Comment by MunWolf** [comment]
@CatGirls420-NerevarII Yes Blizzard implements macro detection but they are also a rich company with specialized testers etc, problem with implementing macro detection here would be to implement it well enough that it would not introduce false positives, we don't have enough players that we can afford to lose some because we were "testing" macro detection.

Then there is the development time we would have to sink into it and I don't think many of our current developers would be motivated to take this on.

You could always try your hand at it and send us a PR but be prepared to wait a long time before it gets accepted since we would not want it breaking games for non macro users.

Maybe it would be more likely to be accepted if it was an option you had to enable on the server.

**Comment by anjew175** [comment]
> blizzard implements anti-macro, and for many, very good, reasons.

But its like you said, for many good reasons. A macro in SC is completely different from what you would use ORA. The time they save is negligible, you can stack the same amount in the start period of the game and just pause it. I'd argue that those top players who use a macro are still just as good without it.
The only reason macro programs are used is to get around the shortcomings of ORA's queuing system, and they are used less frequently during gameplay than they would in SC. In SC you can't stack as many units to be built as in ORA. 

There is an actual root problem for why players are doing this. I feel the problem should be addressed at its source. Whether that's limiting how many units you can actively have being built (which would increase the skill cap of the game) or implementing an infinite queue (which is unlikely to happen), those are the true answers to the problem and anything else will just fall into the constant cycle of macro users getting around limitations.

**Comment by oraservers** [comment]
1. Need to figure out how it would be done in three+ different platforms and releases
2. No current data on the need for this from an engine standpoint 
3. There are exceptions for macro use (such as, people with disabilities, people using specific peripherals)
4. No clarity on the threshold for what level of APM (if thats the right metric), software/hardware/other acceleration/deceleration/automation.

This should be categorized as an idea with no specific timeline

**Comment by CatGirls420-NerevarII** [comment]
In the competitive scene, both players are supposed to have the same set up. If player 1 has macros and hardware for it, but player 2 doesnt, or can't use them for whatever reason, then player 1 has a clear advantage. That's not competitive, that's playing the system to get one up on your opponent.

I don't have hardware for macros (or maybe I do, never bothered to see if I can use macros) and don't intend on getting any either. Idk using macros just seems....well, a lot of words I shouldn't say.

I have ideas on how to make macro detection work but I have so much going in my life I'm nit-picking at things slowly getting a million thing's done. If time permits, I would love to compile code for this.

**Comment by Smittytron** [comment]
If we could add the number of units currently queued to the production tab in spectator UI, like was done with the number of army units in #16709, production macros would be very easy to spot.

**Comment by KOYK** [comment]
I still don't see the point in this. As being said before adding a 100 units or 10 in queue makes no difference in OpenRa.

**Comment by penev92** [comment]
Also I thought we had special shortcuts and incantations and stuff to queue great amounts of units at once?

**Comment by Smittytron** [comment]
> Also I thought we had special shortcuts and incantations and stuff to queue great amounts of units at once?

You can queue one unit at a time or 5. If you can visually see how much of what someone is queuing at a time and it's not 1 or 5, you'd know cheating is occurring.

**Comment by KOYK** [comment]
"cheating" Is a strong word to use here, people might have disabilities or being limited by other factors like hardware.

So now that I think of it, adding this might even have a negative impact on the image of certain players who might indeed have to use a macro program due to those limitations, and I can see this turning into a witch hunt. With people being accused wrongfully.

And again the number of queued units makes no difference in OpenRa.

> you'd know cheating is occurring

If you are looking for ways to generally detect cheaters, you should make a new issue that aims into that.

**Comment by anjew175** [comment]
>  cheating

in your personal opinion

**Comment by Leo512bit** [comment]
This is what happens when you consider button mashing "skill" rather than actual strategy.
This is a well-deserved development that everyone should've seen coming.
