### ISSUE TITLE
Infantry animation glitches when leaving the barracks

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#17252]
Regression from a10af382b43b4b56950ea811fa183c472248e6cd

It looks like we are flicking between moving/idle during the first couple of ticks.

**Comment by pchote** [comment]
The first couple of ticks look like (tick | state change):
```
203 (not in world) | Idle -> Waiting
204 | Waiting -> Moving
205 | Moving -> Waiting
206 | Waiting -> Moving
```

**Comment by tovl** [comment]
This was fixed already in #16938. Something has regressed this again after that.

**Comment by pchote** [comment]
The issue was that the switch from explicit `Mobile.IsMoving` to implicit `Mobile.CurrentMovementTypes` was not accounting for the "old" state during creation, so always considered units to be moving during the first tick.

**Comment by tovl** [comment]
I gathered that from the PR already, but it is only half the story. The question is: What changed the behaviour in ae34410? This could signify a second problem that we are sweeping under the rug now.

The thing is that this should not have been creating problems for units with `returnToCellOnCreation == true` and `creationActivityDelay == 0` in the first place, because those units actually _are_ moving on the first tick. In fact, on the PR, those units will now visibly stand still for one tick, when they should just "hit the ground running". It seems that something in ae34410 somehow caused an extra tick delay.

**Comment by pchote** [comment]
> The question is: What changed the behaviour in ae34410?

The value of `ToSubCell` that `Mobile` sees during its first tick.

The glitch was first re-regressed by 68cee1d97c53243f04b41fe8c85d674faaa53e10. The problem remained on bleed through to 33bba98773, and disappeared again when 0e7e1db1eb reverted it. The sub-cell is initialized to `DefaultSubCell` so the check against `SubCell.Any` in `MoveIntoWorldActivity` fails and the subcell is not touched.

ae34410 restores the subcell recalculation by defining `recalculateSubCell: true`, so the subcell is reassigned (`ReturnToCell` ticks *before* `Mobile`), so the unit is seen to have moved.

**Comment by tovl** [comment]
Interesting. It turns out that the actual problem is with the facing of the unit: The `FacingInit` that is calculated by the `Production` trait becomes outdated when the subcell is recalculated by `ReturnToCellActivity`. This means that a one-tick `Turn` is triggered by the marginal facing difference. This then shows as a visual hiccup.

The solution is to reset `mobile.Facing` after the subcell recalculation. You can quickly check this by adding
```
var toPos = self.World.Map.CenterOfSubCell(cell, subCell);
mobile.Facing = (toPos - pos).Yaw.Facing;
```
inside `ReturnToCellActivity.Tick` after `mobile.SetVisualPosition(self, pos)`.

**Comment by pchote** [comment]
Nice work debugging this, although its not clear how we could fix this in the short term without risking more regressions. Overriding the facing in `ReturnToCellActivity` would run against the goal of it being a general activity that isn't explicitly tied to returning units into the world - ideally we would remove `recalculateSubCell` completely and leave that (if needed) to the code that is setting the cell/centerpos/facing in the first place.

The current release behaviour already has units standing for a single tick before moving, so IMO we would be best to defer anything further to a future cycle when we can also tackle #16486.

**Comment by reaperrr** [comment]
I think #17253 is good enough for the upcoming release. We really need to get that new release out sooner rather than later, so anything that risks breaking prep elsewhere should be avoided as much as possible for now.
