### ISSUE TITLE
Random crash at startup

### ISSUE THREAD

**Issue by Townes27** [OpenRA/OpenRA#7918]
I'm suddenly getting crashes after starting the game and then choosing multiplayer.
The snippet is from release-20141029 which crashes immediately when I choose multiplayer.
The exception is identical with playtest-20150405 and playtest-20150408 when I choose "incompatible" in multiplayer mode. It does not crash the playtests if I do not choose to see the "incompatible" servers.

<pre><code>
Platform is Linux
Using SDL 2 with OpenGL renderer
Desktop resolution: 1920x1200
No custom resolution provided, using desktop resolution
Using resolution: 1920x1200
Detected OpenGL version: 3.0
Using OpenAL sound engine
Using default device
Available mods:
        cnc: Tiberian Dawn (release-20141029)
        d2k: Dune 2000 (release-20141029)
        modchooser: Mod Chooser (release-20141029)
        ra: Red Alert (release-20141029)
Loading mod: ra
Exception of type `System.ArgumentException`: A null reference or invalid value was found [GDI+ status: InvalidParameter]
  at System.Drawing.GDIPlus.CheckStatus (Status status) [0x00000] in <filename unknown>:0 
  at System.Drawing.Bitmap.LockBits (Rectangle rect, ImageLockMode flags, PixelFormat format, System.Drawing.Imaging.BitmapData bitmapData) [0x00000] in <filename unknown>:0 
  at System.Drawing.Bitmap.LockBits (Rectangle rect, ImageLockMode flags, PixelFormat format) [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Drawing.Bitmap:LockBits (System.Drawing.Rectangle,System.Drawing.Imaging.ImageLockMode,System.Drawing.Imaging.PixelFormat)
  at OpenRA.Graphics.Util.FastCopyIntoSprite (OpenRA.Graphics.Sprite dest, System.Drawing.Bitmap src) [0x00000] in <filename unknown>:0 
  at OpenRA.Graphics.SheetBuilder.Add (System.Drawing.Bitmap src) [0x00000] in <filename unknown>:0 
  at OpenRA.MapCache.LoadAsyncInternal () [0x00000] in <filename unknown>:0 
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentException: A null reference or invalid value was found [GDI+ status: InvalidParameter]
  at System.Drawing.GDIPlus.CheckStatus (Status status) [0x00000] in <filename unknown>:0 
  at System.Drawing.Bitmap.LockBits (Rectangle rect, ImageLockMode flags, PixelFormat format, System.Drawing.Imaging.BitmapData bitmapData) [0x00000] in <filename unknown>:0 
  at System.Drawing.Bitmap.LockBits (Rectangle rect, ImageLockMode flags, PixelFormat format) [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Drawing.Bitmap:LockBits (System.Drawing.Rectangle,System.Drawing.Imaging.ImageLockMode,System.Drawing.Imaging.PixelFormat)
  at OpenRA.Graphics.Util.FastCopyIntoSprite (OpenRA.Graphics.Sprite dest, System.Drawing.Bitmap src) [0x00000] in <filename unknown>:0 
  at OpenRA.Graphics.SheetBuilder.Add (System.Drawing.Bitmap src) [0x00000] in <filename unknown>:0 
  at OpenRA.MapCache.LoadAsyncInternal () [0x00000] in <filename unknown>:0 
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0 
</code></pre>

**Comment by Phrohdoh** [comment]
We have discovered that this crash is caused by [this map](http://resource.openra.net/maps/2748).
Please delete it until a fix is released.

**Comment by RoosterDragon** [comment]
That map is currently providing a custom preview with a pixel format of ```PixelFormat.Format24bppRgb```.

This is falling over when we later expect it to be a different format in [FastCopyIntoSprite](https://github.com/OpenRA/OpenRA/blob/6e14d96815a41308d5408300f1b0c0bbfad3e72f/OpenRA.Game/Graphics/Util.cs#L75). mono crashes, MS happens to keep going and not do anything bad.

```c#
var bd = src.LockBits(src.Bounds(),
				ImageLockMode.ReadWrite, PixelFormat.Format32bppArgb);
```

We should probably convert anything in a different format when we receive it in [MapPreview](https://github.com/OpenRA/OpenRA/blob/6e14d96815a41308d5408300f1b0c0bbfad3e72f/OpenRA.Game/Map/MapPreview.cs#L157) to ensure we have ```PixelFormat.Format32bppArgb```.

**Comment by Townes27** [comment]
Thank you for the quick response.
I don't have that map installed.
Until a minute ago I only had these three:
a-pattern-of-islands-1.oramap
Defcon_1__Gamma_Quadrant_balanced-1.oramap
Double_Snow_Ridge-2.oramap

I deleted them one by one and tested it, but even after deleting them all I still get the same crash.

**Comment by RoosterDragon** [comment]
The crash happens when the preview is downloaded to be shown on the multiplayer lobby screen. So unfortunately just deleting it won't be enough. If you go into multiplayer and a server with that map is running you'll get the crash.

**Comment by pchote** [comment]
It continues to crash because the game is fetching the preview from the resource center when somebody hosts a server with it.

**Comment by Townes27** [comment]
Okay, thank you.
