### ISSUE TITLE
UnauthorizedAccessException when saving maps in system folders

### ISSUE THREAD

**Issue by airetaM** [OpenRA/OpenRA#9430]
my mapeditor crashes when i want to create new map

i will use the old editors meanwhile

here is the exception.log :

Tiberian Dawn Mod at Version release-20150919
on map b0f941e404b8113179ed8c358982f99d3b1021c5 (shellmap by Chris Forbes).
Operating System: Linux (Unix 3.13.0.61)
Runtime Version: Mono 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1) CLR 4.0.30319.17020
Exception of type `System.UnauthorizedAccessException`: Access to the path "/usr/lib/openra/mods/cnc/maps/Rainy Forest.oramap" is denied.
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) [0x00000] in <filename unknown>:0 
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize) [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int)
  at System.IO.File.Create (System.String path, Int32 bufferSize) [0x00000] in <filename unknown>:0 
  at System.IO.File.Create (System.String path) [0x00000] in <filename unknown>:0 
  at ICSharpCode.SharpZipLib.Zip.ZipFile.Create (System.String fileName) [0x00000] in <filename unknown>:0 
  at OpenRA.FileSystem.ZipFile..ctor (System.String filename, Int32 priority, System.Collections.Generic.Dictionary`2 contents) [0x00000] in <filename unknown>:0 
  at OpenRA.FileSystem.GlobalFileSystem.CreatePackage (System.String filename, Int32 order, System.Collections.Generic.Dictionary`2 content) [0x00000] in <filename unknown>:0 
  at OpenRA.Map.Save (System.String toPath) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Widgets.Logic.SaveMapLogic+<SaveMapLogic>c__AnonStorey0.<>m__2 () [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Widgets.ButtonWidget.<ButtonWidget>m__A (MouseInput _) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Widgets.ButtonWidget.HandleMouseInput (MouseInput mi) [0x00000] in <filename unknown>:0 
  at OpenRA.Widgets.Widget.HandleMouseInputOuter (MouseInput mi) [0x00000] in <filename unknown>:0 
  at OpenRA.Widgets.Ui.HandleInput (MouseInput mi) [0x00000] in <filename unknown>:0 
  at OpenRA.DefaultInputHandler+<OnMouseInput>c__AnonStorey2.<>m__0 () [0x00000] in <filename unknown>:0 
  at OpenRA.Sync.CheckSyncUnchanged[Boolean] (OpenRA.World world, System.Func`1 fn) [0x00000] in <filename unknown>:0 
  at OpenRA.DefaultInputHandler.OnMouseInput (MouseInput input) [0x00000] in <filename unknown>:0 
  at OpenRA.Renderer.Sdl2.Sdl2Input.PumpInput (IInputHandler inputHandler) [0x00000] in <filename unknown>:0 
  at OpenRA.Renderer.Sdl2.Sdl2GraphicsDevice.PumpInput (IInputHandler inputHandler) [0x00000] in <filename unknown>:0 
  at OpenRA.Graphics.Renderer.EndFrame (IInputHandler inputHandler) [0x00000] in <filename unknown>:0 
  at OpenRA.Game.RenderTick () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Loop () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Run () [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Run (System.String[] args) [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0

**Comment by pchote** [comment]
There are two problems here:

* we need to catch any exceptions during save and display the error instead of crashing
* we need to not offer the system map dir as a save location if it isn't writable.

**Comment by pchote** [comment]
This issue keeps on catching people out, so adding to the milestone.  It doesn't need to block the next playtest, but we definitely need to fix it before the final release.

**Comment by penev92** [comment]
The worst part of this was fixed. Removing from the milestone.

**Comment by MichaelLHansen** [comment]
Sorry for my ignorance, but I just installed the playtest and I can't save maps. I can get into an existing map, but making a new one or saving the existing one, crashes the editor. You said "The worst part of this was fixed.", but I still can't save maps (re-downloaded everything today). Did you mean it's fixed for the next playtest release? If so, I can be patient. If not, then whatever you fixed is still broken on Ubuntu 14.04 and my log is showing the same error, where you don't have permission to access the folder.

Log Text:
``Red Alert Mod at Version playtest-20151031
on map b00241ad2d4caaada8a650309bc716c3eb3de1c3 (Tournament Island by Scott_NZ).
Operating System: Linux (Unix 3.13.0.68)
Runtime Version: Mono 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1) CLR 4.0.30319.17020
Exception of type `System.UnauthorizedAccessException`: Access to the path "/usr/lib/openra/mods/ra/maps/tournament-island.oramap" is denied.
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options)``

**Comment by pchote** [comment]
It's been fixed for the next playtest, which should be released within the next hour or two.

**Comment by GraionDilach** [comment]
You can also change the Directory yourself into `^mods/ra` which is within your `/home/username/.openra` folder and thereby you have write access to it. The "fix" itself is to offer this location as default.

**Comment by MichaelLHansen** [comment]
Wow you guys are crazy fast. Thanks for the prompt feedback. I'll just chill until tomorrow and get the new playtest. I'd set things myself GraionDilach, but I'd be likely to jack something up.
